const:
  default-page-size: 20


file:
  directory: D:/Students/yjw/teamtodo/files

mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: teamtodo
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/team_todo
    username: root
    password: green502
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      max-file-size: 15MB


springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true