file:
  directory: D:/ksj/download/project_1

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: project_1
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/team_todo
    username: root
    password: green502
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true